
{% set version = "0.7.4" %}

package:
  name: gridded
  version: {{ version }}

source:
  url: https://github.com/NOAA-ORR-ERD/gridded/archive/v{{ version }}.tar.gz
  sha256: fc8ada0bef0cbc5fa1f27383d7e3b5e8f438d8f6f38baea20c03cdf07c7a89cf
  
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - python-dateutil
    - netcdf4
    - cell_tree2d

test:
  requires:
    - pytest
    - python {{ python_min }}
    - pooch

  imports:
    - gridded

  commands:
    - python -c "import gridded; assert gridded.__version__ == '{{ version }}'"
    - pytest --pyargs gridded

about:
  home: https://github.com/NOAA-ORR-ERD/gridded
  license: BSD-3-Clause
  license_file: LICENSE
  summary: |
    A library designed to represent grid-aligned data and provide a variety of
    processing functions, netCDF file reading/writing, and CF, UGrid, and SGrid
    standard compatibility.

  description: |
    Gridded is a unification of the pysgrid, pyugrid, and a data representation
    layer that is designed to provide an intuitive and flexible system for
    reading and representing gridded data from a variety of sources. It is also
    a library to contain useful functions for processing gridded data.

extra:
  recipe-maintainers:
    - jay-hennen
    - ChrisBarker-NOAA
