# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Z/KiwoHbyhyGr4cegdA3p9/1BmIuOIuyAho59p6sHO6LSkhrsY0JIims0vk1FdmdPN2Pznj3kGdgqbu3VJ6Mu3eue0oQEjtVaX2g3Y6EZ6XqWpspswGD7MM5IfOGosjP74WrMvvKaUMgxu4TfTzgF9BaEKZCgDsWx5qRrTXhVysP03RBANC6qqGbBA9W0FDgFvB+W+vUA9bi+oFEt34uqkmBj3PrtFM5a9L+s18CDDQBdiHDyBIPFX44emzNUkp3tcZeq+zkD2CU+AQIMwrPUzljsrRU8JUcGjg/TFUBoL5M/nvR/BNiiv2MLbp7htXQK0M4s+pfNF1uOy/CV7sG7EbXJ74zwflA1ZEwJHDHfHP5rlQ11tk+zXiac5N/sJXQS1b2ZJm/5atyEo+UAw6yb/Xa16NoT/Q40KiubHqB/g+7Xl0L7DZv/BexY9QsyPJSyaz5zjzDPcAsvAdxjSXncfPGPsZ4j4fedZSGV8z71l9nHYBOXNiC+HpTWJJHLWz/thudMtvfF0F+Cv80ocDihnS00DpO45vM/WxM15pDxIPzk4Qnp/G2+EZheP5XwWH6LzHZLIQBjL3DcVMpFmsjlBqV4nOBa/w+Kh4jZoS+aH4N76D99ZNYutgogJ+umz+KPNS1vKds/bAf28RjDMqgZDs+ozg0nO9nyRF08kCQLUE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
